
***NOTE: Messages are organized per MPI process in separate sections below.


**********************************
*  Message file output, cpu #1   *
**********************************


 STEP 1  ORIGIN 0.0000


**********************************
*  Message file output, cpu #2   *
**********************************


  The maximum ratio of deformation speed to wave speed is 0.40000 in element
  51 of instance PART-1-3 at increment 24861.


  The maximum ratio of deformation speed to wave speed is 1.2000 in element 41
  of instance PART-1-3 at increment 24862.

