
***NOTE: Messages are organized per MPI process in separate sections below.


**********************************
*  Message file output, cpu #1   *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------

 STEP 1  ORIGIN 0.0000


**********************************
*  Message file output, cpu #2   *
**********************************

-------------------------------------------------------------------------------

  INFORMATION REGARDING INITIAL CONTACT OVERCLOSURES FOR NEWLY DEFINED GENERAL
  CONTACT INTERACTIONS IN STEP 1

-------------------------------------------------------------------------------
